excel:
  prefix:
    staffCode: PH34449
    name: Nguyen Minh Tu
    accountFPT: tunmph34449@fpt.edu.vn
    accountFE: tunmph34449fe.edu.vn
    contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    historyImport: import-history.txt
app:
  verify:
    user: user1
    type: 0
    key: Tm9uZyBIb2FuZyBWdQ==
spring:
  application:
    name: StaffManager
  datasource:
    url: jdbc:mysql://localhost:3306/exam_distribution_testt
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
